### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by Danielalab** [YaninaPortal/lim-2018-05-bc-core-pm-socialnetwork#28]
El proyecto cumple con los requerimientos de funcionalidad y los tests **no cumplen** con los porcentajes mínimos requeridos.
- Html : recuerda que tu html debe pasar el siguiente validador https://validator.w3.org/nu/?doc=https%3A%2F%2Fdianaapz.github.io%2Flim-2018-05-bc-core-pm-socialnetwork%2Fsrc%2Flogin.html
y mantener la guía de estilos HtmlHint (http://htmlhint.com/)
![image](https://user-images.githubusercontent.com/32286663/43980683-c08299b0-9cb4-11e8-8485-820d43972e67.png).
Te recomendamos utilizar guiones para tus clases y ids en lugar de camel case (ver imagen)
![image](https://user-images.githubusercontent.com/32286663/43981523-c5c8809e-9cb7-11e8-94b7-73bfdef47109.png)
Igualmente ten en cuenta el buen uso de etiquetas html semánticas ya que en este caso utilizas la etiqueta **header como un section** (ver resgister.html) , Te recomendamos utilizar etiquetas como section y main y mantener una indentación consistente.

Js :  Te recomendamos ser consistente en la **indentación** de 2 espacios, igualmente una vez ya desplegado tu proyecto puedes eliminar los **console.log** que utilizaste en desarrollo. También debes ser consistente en el uso de comillas simples y elegir una para ser uniforme en el código, al igual de utilizar un punto y coma al final de cada sentencia.
Ten en cuenta utilizar la sintaxis de **ES6** (ver imagen) utilizando **const y let , arrow function**
![image](https://user-images.githubusercontent.com/32286663/43983594-ff48b10a-9cc0-11e8-89af-6c7c1443e1ce.png)
Igualmente podrías declarar estas variables (ver imagen) utilizando const ya que no les reasignas un nuevo valor.
![image](https://user-images.githubusercontent.com/32286663/43983762-15fb9fba-9cc2-11e8-9fb7-e5cca3bbefb2.png)

Css: Te recomendmaos mantener una indentación uniforme, también recuerda hacer uso de clases para reutilizar estilos. (ver imagen)
![image](https://user-images.githubusercontent.com/32286663/43981302-e4839c54-9cb6-11e8-8fce-70c4c1885e7b.png)
Te recomendmaos mantener uniformidad en el tipo de color que utilizaras en el desarrollo de tus estilos.
![image](https://user-images.githubusercontent.com/32286663/43981330-0171defc-9cb7-11e8-876c-321ca16646f9.png)

**Comment by YennyCastillo** [comment]
Gracias Daniela por el feedback, lo tendremos en cuenta para mejorar la red social y para nuestros futuros proyectos.
